name: last_launcher
description: Last Launcher
publish_to: "none"
version: 1.2.1+17

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon.png
  fonts:
    - family: AkkuratRegular
      fonts:
        - asset: assets/fonts/Akkurat-Regular.ttf
    - family: RobotoMonoMedium
      fonts:
        - asset: assets/fonts/Roboto-Mono-Medium.ttf
    - family: RobotoMonoLight
      fonts:
        - asset: assets/fonts/Roboto-Mono-Light.ttf
    - family: RobotoMonoThin
      fonts:
        - asset: assets/fonts/Roboto-Mono-Thin.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Raleway-Thin
      fonts:
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: Laconic
      fonts:
        - asset: assets/fonts/Laconic_Light.otf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf
